# Generated by Django 3.2.6 on 2021-09-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='paypal_comissions',
            new_name='paypal_commissions',
        ),
    ]
