# Generated by Django 3.2.6 on 2021-09-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0002_rename_paypal_comissions_bank_paypal_commissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='Statistics',
        ),
    ]
