# Generated by Django 3.2.6 on 2021-09-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0003_rename_bank_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_entries', models.PositiveIntegerField()),
                ('mobile_api_requests', models.PositiveIntegerField()),
                ('new_devices', models.PositiveIntegerField()),
            ],
        ),
    ]
