# Generated by Django 3.2.6 on 2021-09-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0004_dailystatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatistics',
            name='article_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailystatistics',
            name='mobile_api_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailystatistics',
            name='new_devices',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
