# Generated by Django 3.2.6 on 2021-09-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0005_auto_20210916_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatistics',
            name='app_launched_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
