# Generated by Django 3.2.6 on 2021-09-16 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0006_dailystatistics_app_launched_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatistics',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
