# Generated by Django 3.2.6 on 2021-09-16 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0007_dailystatistics_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatistics',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
