# Generated by Django 3.2.6 on 2021-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0008_alter_dailystatistics_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatistics',
            name='personal_notes_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='personal_notes_edited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='personal_notes_entries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
