# Generated by Django 2.2.20 on 2021-08-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210815_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumtoken',
            name='token_code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
