# Generated by Django 2.2.20 on 2021-08-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_premiumtoken_paypal_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumtoken',
            name='paypal_subscription_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
