# Generated by Django 2.2.20 on 2021-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20210815_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpaymenttoken',
            name='given_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='afterpaymenttoken',
            name='payer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='afterpaymenttoken',
            name='plan',
            field=models.CharField(blank=True, choices=[('3M', '3M'), ('6M', '6M'), ('12M', '12M')], max_length=3),
        ),
        migrations.AddField(
            model_name='afterpaymenttoken',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
