# Generated by Django 2.2.20 on 2021-08-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20210815_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpaymenttoken',
            name='plan_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
