# Generated by Django 3.2.6 on 2021-08-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_afterpaymenttoken_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterpaymenttoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
