# Generated by Django 3.2.6 on 2021-08-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20210818_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpaymenttoken',
            name='email_address',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
