# Generated by Django 3.2.6 on 2021-08-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_afterpaymenttoken_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterpaymenttoken',
            name='email_address',
            field=models.EmailField(default='default@default.default', max_length=254),
        ),
    ]
