# Generated by Django 3.2.6 on 2021-08-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_afterpaymenttoken_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterpaymenttoken',
            name='active',
        ),
        migrations.AddField(
            model_name='afterpaymenttoken',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('CANCELED', 'CANCELED')], max_length=9),
        ),
    ]
