# Generated by Django 3.2.6 on 2021-09-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20210820_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paypal_comissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.device')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
