# Generated by Django 3.2.6 on 2021-09-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20210911_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paypal_comissions',
            new_name='paypal_commissions',
        ),
    ]
