# Generated by Django 3.2.6 on 2021-10-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_alter_supportticketmessage_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='types',
            new_name='type',
        ),
    ]
