# Generated by Django 3.2.6 on 2021-10-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_alter_supportticketmessage_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketmessage',
            name='was_seen',
            field=models.BooleanField(default=False),
        ),
    ]
