# Generated by Django 3.2.6 on 2022-02-16 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0029_auto_20220216_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
