# Generated by Django 3.2.6 on 2022-02-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0030_alter_personalnote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_device',
        ),
        migrations.RemoveField(
            model_name='category',
            name='super_category',
        ),
        migrations.DeleteModel(
            name='DeviceAction',
        ),
        migrations.DeleteModel(
            name='SuperCategory',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
