# Generated by Django 3.2.6 on 2022-02-16 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0031_auto_20220216_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='device',
        ),
        migrations.RemoveField(
            model_name='supportticketmessage',
            name='device',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
