# Generated by Django 3.2.6 on 2022-02-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0032_auto_20220216_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='premium_token',
        ),
        migrations.DeleteModel(
            name='AfterPaymentToken',
        ),
        migrations.DeleteModel(
            name='BeforePaymentToken',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
