# Generated by Django 3.2.6 on 2022-04-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_fontsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fontsettings',
            name='font_style',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('ITALIC', 'italic')], default='NORMAL', max_length=6),
        ),
        migrations.AddField(
            model_name='fontsettings',
            name='font_weight',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('BOLD', 'bold')], default='NORMAL', max_length=6),
        ),
    ]
