# Generated by Django 3.2.6 on 2022-04-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220424_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='fontsettings',
            name='background_color',
            field=models.TextField(default='#FFFFFF'),
        ),
        migrations.AlterField(
            model_name='fontsettings',
            name='font_style',
            field=models.CharField(choices=[('normal', 'normal'), ('italic', 'italic')], default='normal', max_length=6),
        ),
        migrations.AlterField(
            model_name='fontsettings',
            name='font_weight',
            field=models.CharField(choices=[('normal', 'normal'), ('bold', 'bold')], default='normal', max_length=6),
        ),
    ]
