# Generated by Django 3.2.6 on 2022-04-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220425_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category_settings',
            field=models.JSONField(default=[{'codigos': ['cc', 'cpc', 'crp', 'crcivil'], 'id': 0, 'key': 'extra_0', 'themeColor': '#42C6A5', 'thumbnail': 'BG_1', 'title': 'Área Civil'}, {'codigos': ['cp', 'cpp', 'rgit'], 'id': 1, 'key': 'extra_1', 'themeColor': '#E5C184', 'thumbnail': 'BG_2', 'title': 'Área Penal'}, {'codigos': ['cpa', 'cpta'], 'id': 2, 'key': 'extra_2', 'themeColor': '#98A6EF', 'thumbnail': 'BG_3', 'title': 'Administrativo'}, {'codigos': ['ct', 'cpt'], 'id': 3, 'key': 'extra_3', 'themeColor': '#64BEE1', 'thumbnail': 'BG_4', 'title': 'Trabalho'}, {'codigos': ['csc', 'crcomercial', 'ncpi', 'cvm'], 'id': 4, 'key': 'extra_4', 'themeColor': '#657286', 'thumbnail': 'BG_6', 'title': 'Comercial'}, {'codigos': ['lgt', 'cppt', 'rgit'], 'id': 5, 'key': 'extra_5', 'themeColor': '#98A6EF', 'thumbnail': 'BG_3', 'title': 'Fiscal'}, {'codigos': ['ce'], 'id': 6, 'key': 'extra_6', 'themeColor': '#FC9BA1', 'thumbnail': 'BG_5', 'title': 'Outros'}]),
        ),
    ]
