# Generated by Django 3.2.6 on 2022-02-26 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforePaymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_subscription_id', models.CharField(max_length=128, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AfterPaymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(blank=True, max_length=50)),
                ('plan', models.CharField(blank=True, choices=[('3M', '3M'), ('6M', '6M'), ('12M', '12M')], max_length=3)),
                ('plan_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('CANCELED', 'CANCELED')], max_length=9)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('before_payment_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paypal.beforepaymenttoken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
